spring:

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:49161:xe
    username: system
    password: oracle

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    rest:
      base-path: /api

  activemq:
    broker-url: tcp://localhost:61616

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server.port: 8090
server.servlet.context-path: /hello
#inject custom value
project:
  author: Peng
  name: spring-demo
